def test_wrong():
    assert 1 == 1  # Fails on purpose

